import streamlit as st
import streamlit_book as stb
import time
import random

def add_logo():
    st.markdown(
        """
        <style>
            [data-testid="stSidebarNav"] {
                background-image: url(https://upload.wikimedia.org/wikipedia/commons/2/2a/Microsoft_365_Copilot_Icon.svg);
                background-repeat: no-repeat;
                background-position: 20px 20px;
            }
            [data-testid="stSidebarNav"]::before {
                content: "Student Companion";
                margin-left: 20px;
                margin-top: 20px;
                font-size: 30px;
                position: relative;
                top: 100px;
            }
        </style>
        """,
        unsafe_allow_html=True,
    )

with st.sidebar:
    add_logo()
    
with stb.echo("below", "Here is a nice **Hint**"):
    stb.multiple_choice("### Thats your question generated by GPT",
                        {"Das richtige ✅":True,
                         "Falsch 😅":False,
                         "pyspark":False,
                         "vulpix":False}
                       )
    